table dAcoes
	lineageTag: e037a74c-f20f-4b0b-aef2-596deae33526

	column AcaoID
		dataType: string
		lineageTag: 9835d6a7-ee3d-4819-bfb5-c992e2c2abe1
		summarizeBy: none
		sourceColumn: AcaoID

		annotation SummarizationSetBy = Automatic

	column TipoAcao
		dataType: string
		lineageTag: 72831a7c-ece3-4d40-808b-046b60a19542
		summarizeBy: none
		sourceColumn: TipoAcao

		annotation SummarizationSetBy = Automatic

	partition dAcoes = m
		mode: import
		queryGroup: 'Tabelas Dimensões'
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(Caminho&"Detalhes_Chamados.xlsx"), null, true),
				    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Cabeçalhos Promovidos",{"CodAcao", "TipoAcao"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Duplicatas Removidas",{{"CodAcao", type text}, {"TipoAcao", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"CodAcao", "AcaoID"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

